ERROR_MESSAGE:
  EMPTY: '値を入力してください。'
  HALF_WIDTH_SPACE: '5つのカード指定文字を半角スペース区切りで入力してください。（例："S1 H3 D9 C13 S11"）'
  DUPLICATE: 'カードが重複しています。'
  VALID_SUIT_NUM: '半角英字大文字のスート（S,H,D,C）と数字（1〜13）の組み合わせでカードを指定してください。'
